steps:
  # Las siguientes 3 tareas utilizan el comando "docker" de GCP Cloud Builders.
  # La primera tarea llama al comando "docker pull" para descargar una imagen de Docker del registro
  # de GCP Container Registry.
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'pull',
      'us-central1-docker.pkg.dev/${PROJECT_ID}/api-malformed-names/app:qa-$COMMIT_SHA'
    ]
  # Aquí se pueden agregar pasos adicionales para testing automatico y pruebas de ambiente.
  # Se llama al comando "docker push" para subir la imagen etiquetada al registro de GCP Container Registry.
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/${PROJECT_ID}/api-malformed-names/app:qa-$COMMIT_SHA'
    ]